### ISSUE TITLE
Ride isn't quite working...

### ISSUE THREAD

**Issue by Internetpilot** [TechzoneMC/SonarPet#1]
First of all, soooooooo happy to see this!  Thank you!  I will gladly donate $ for this new version and continue to donate to keep this plugin updated!

I know you just posted a release of this, and it probably isn't ready for primetime quite yet, but I'd thought I'd let you know that the command /pet ride doesn't work.  It almost seems like that's the /pet call function now.  What does allow you to ride a pet is the command /pet hat.  This happens whether using the command line or the pet menu.  

Edit:  Also quite a few of the pets cannot be controlled when riding even when you trick it with the /pet hat command.  For example, I can ride and move on a cow, mooshroom, chicken, etc., with the /pet hat command, but I cannot get an Iron Golem, Creeper, Zombie, etc. to move when riding them.  

Here's the error from the console that happens every time I use /pet ride or choose the carrot on a stick from the pet selector menu:

`17:26:43 WARN]: [SonarPet] Task #29 for SonarPet v1.0.0 generated an exception
java.lang.IllegalStateException: Circular entity riding! EntityPlayer['InternetPilot'/249, l='Moosh Amped', x=1995.75, y=90.32, z=-951.25](InternetPilot at 1995.7499999701977,90.32499998211861,-951.2500000298023) EntityZombiePet['Zombie Pet'/9845, l='Moosh Amped', x=1995.75, y=90.00, z=-951.25]
        at com.google.common.base.Preconditions.checkState(Preconditions.java:200) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at net.minecraft.server.v1_9_R1.Entity.o(Entity.java:1672) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at net.minecraft.server.v1_9_R1.Entity.a(Entity.java:1641) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at net.minecraft.server.v1_9_R1.EntityInsentient.a(EntityInsentient.java:1079) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at net.minecraft.server.v1_9_R1.Entity.startRiding(Entity.java:1629) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftEntity.setPassenger(CraftEntity.java:326) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at com.dsh105.echopet.compat.api.util.INMS.mount(INMS.java:44) ~[?:?]
        at com.dsh105.echopet.api.pet.Pet$1.run(Pet.java:311) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]`

**Comment by Techcable** [comment]
Fixed as of 539e303

**Comment by Internetpilot** [comment]
Mounting them for riding definitely works now, but now I can no longer reliably control any of the pets when riding them.  I cannot move forward or backward at all and can only jump in place.   

Console errors:

`[22:19:27] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SonarPet v1.0.1-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1852) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing 'pet wither' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	... 15 more
Caused by: com.dsh105.echopet.compat.api.registration.PetRegistrationException: java.lang.IllegalStateException: Failed to create pet object for InternetPilot
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:121) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	... 15 more
Caused by: java.lang.IllegalStateException: Failed to create pet object for InternetPilot
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:85) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	... 15 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	... 15 more
Caused by: java.lang.IllegalStateException: Failed to create EntityPet object for InternetPilot
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:99) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:142) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:49) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:35) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:72) ~[?:?]
	at com.dsh105.echopet.api.pet.type.WitherPet.<init>(WitherPet.java:33) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	... 15 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:91) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:142) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:49) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:35) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:72) ~[?:?]
	at com.dsh105.echopet.api.pet.type.WitherPet.<init>(WitherPet.java:33) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	... 15 more
Caused by: java.lang.IllegalArgumentException: Duplicate id value for 13!
	at net.minecraft.server.v1_9_R1.DataWatcher.register(DataWatcher.java:63) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at com.dsh105.echopet.compat.nms.v1_9_R1.metadata.WrappedDataWatcher.register(WrappedDataWatcher.java:31) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_9_R1.entity.type.EntityWitherPet.initDatawatcher(EntityWitherPet.java:58) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_9_R1.entity.EntityPet.i(EntityPet.java:511) ~[?:?]
	at net.minecraft.server.v1_9_R1.Entity.<init>(Entity.java:184) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.EntityLiving.<init>(EntityLiving.java:120) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.EntityInsentient.<init>(EntityInsentient.java:48) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at net.minecraft.server.v1_9_R1.EntityCreature.<init>(EntityCreature.java:20) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at com.dsh105.echopet.compat.nms.v1_9_R1.entity.EntityPet.<init>(EntityPet.java:107) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_9_R1.entity.type.EntityWitherPet.<init>(EntityWitherPet.java:43) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:91) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:142) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:49) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:35) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:72) ~[?:?]
	at com.dsh105.echopet.api.pet.type.WitherPet.<init>(WitherPet.java:33) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?]
	at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a]
	... 15 more
`
