### ISSUE TITLE
Dev builds don't work

### ISSUE THREAD

**Issue by dejakob1** [TechzoneMC/SonarPet#101]
Build 6 works but isn't compatible with Citizens2, all build above 6 don't load on my server.
Version: Spigot 1.11.2 @ Java 8

Error: [10:44:34 ERROR]: Error occurred while enabling SonarPet v1.1.0-alpha2-dev-9e0c255c (Is it up to date?)

Nothing happens when I run the /pet commands

**Comment by TagCraftMC** [comment]
Getting the same issue. It's trying to download libraries into a directory that ISNT running the plugin?

`
[04:48:44] [Server thread/INFO]: [SonarPet] Loading SonarPet v1.1.0-alpha2-dev-9e0c255c
[04:48:44] [Server thread/INFO]: [SonarPet] Downloading SonarPet's libraries
[04:48:45] [Server thread/INFO]: [SonarPet] Downloading com.google.code.gson:gson:2.2.4 from maven-central
[04:48:45] [Server thread/ERROR]: [SonarPet] Unable to load libraries
java.nio.file.AccessDeniedException: /home/minecraft/multicraft/servers/factions_mining_server/.m2
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:1.8.0_91]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_91]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_91]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source) ~[?:1.8.0_91]
	at java.nio.file.Files.createDirectory(Unknown Source) ~[?:1.8.0_91]
	at java.nio.file.Files.createAndCheckIsDirectory(Unknown Source) ~[?:1.8.0_91]
	at java.nio.file.Files.createDirectories(Unknown Source) ~[?:1.8.0_91]
	at net.techcable.sonarpet.maven.LocalRepository.downloadFrom(LocalRepository.java:33) ~[SonarPet.jar:?]
	at net.techcable.sonarpet.Bootstrap.lambda$onLoad$2(Bootstrap.java:41) ~[SonarPet.jar:?]
	at net.techcable.sonarpet.maven.MavenDependencyInfo.injectDependencies(MavenDependencyInfo.java:39) ~[SonarPet.jar:?]
	at net.techcable.sonarpet.Bootstrap.onLoad(Bootstrap.java:33) [SonarPet.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:306) [Spigot-Latest-CI.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [Spigot-Latest-CI.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [Spigot-Latest-CI.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
`

This plugin is running in factions_server not factions_mining_server...

**Comment by Techcable** [comment]
@dejakob1 Are you getting the same error?
Apparently, java's `user.home` property is incorrect.

**Comment by dejakob1** [comment]
`[01:46:24 ERROR]: Error occurred while enabling SonarPet v1.1.0-alpha2-dev-9e0c255c (Is it up to date?)
java.lang.NullPointerException
        at net.techcable.sonarpet.Bootstrap.onEnable(Bootstrap.java:57) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`

I hope this is any good :-)

**Comment by Techcable** [comment]
@dejakob1 
I need you to [gist](gist.github.com) your _full_ logs, as there should've been errors before that.
