### ISSUE TITLE
Major Console Spam when Spawning In Pets

### ISSUE THREAD

**Issue by RyanEvenstar** [TechzoneMC/SonarPet#11]
Also, I might add that it constantly prompts for a new update. Keep up the good work!

Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to SonarPet v1.0.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom_server.jar:git-Spigot-129f87a-6067e54]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom_server.jar:git-Spigot-129f87a-6067e54]
at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1532) [custom_server.jar:git-Spigot-129f87a-6067e54]
at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [custom_server.jar:git-Spigot-129f87a-6067e54]
at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [custom_server.jar:git-Spigot-129f87a-6067e54]
at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom_server.jar:git-Spigot-129f87a-6067e54]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [custom_server.jar:git-Spigot-129f87a-6067e54]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [custom_server.jar:git-Spigot-129f87a-6067e54]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [custom_server.jar:git-Spigot-129f87a-6067e54]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [custom_server.jar:git-Spigot-129f87a-6067e54]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [custom_server.jar:git-Spigot-129f87a-6067e54]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NoClassDefFoundError: com/dsh105/echopet/libs/com/dsh105/commodus/IdentUtil
at com.dsh105.echopet.compat.nms.v1_9_R1.entity.EntityPet.onInteract(EntityPet.java:284) ~[?:?]
at com.dsh105.echopet.listeners.PetOwnerListener.onPlayerInteractEntity(PetOwnerListener.java:75) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
... 15 more
Caused by: java.lang.ClassNotFoundException: com.dsh105.echopet.libs.com.dsh105.commodus.IdentUtil
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_71]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_71]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_71]
at com.dsh105.echopet.compat.nms.v1_9_R1.entity.EntityPet.onInteract(EntityPet.java:284) ~[?:?]
at com.dsh105.echopet.listeners.PetOwnerListener.onPlayerInteractEntity(PetOwnerListener.java:75) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]

**Comment by Techcable** [comment]
This has been fixed in the development builds.
Please upgrade

**Comment by RyanEvenstar** [comment]
I downloaded the latest build from here on Github. Am I missing something or?

**Comment by Techcable** [comment]
The [development builds](https://ci.techcable.net/job/SonarPets/)
