### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by noy98** [TechzoneMC/SonarPet#111]
[03:26:34] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet Parrot' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Unknown class for hook type PARROT
	at net.techcable.sonarpet.HookRegistryImpl.spawnEntity(HookRegistryImpl.kt:57) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:98) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:85) ~[?:?]
	at com.dsh105.echopet.api.pet.type.ParrotPet.<init>(ParrotPet.kt:11) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:1.8.0_111]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.kt:142) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:241) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:418) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	... 14 more

**Comment by Techcable** [comment]
This should be fixed, as I can successfully spawn parrots on my test server.
If you still have the bug just reply and I'll reopen it.
