### ISSUE TITLE
cast exception

### ISSUE THREAD

**Issue by PhanaticD** [TechzoneMC/SonarPet#114]
```
[15:06:57 WARN]: [SonarPet] Task #2741749 for SonarPet v1.1.0-alpha2-dev-2f35bc2a generated an exception
java.lang.ClassCastException: com.dsh105.echopet.api.pet.type.ZombiePet cannot be cast to com.dsh105.echopet.compat.api.entity.type.pet.ISkeletonPet
        at com.dsh105.echopet.api.PetManager.setData(PetManager.java:668) ~[?:?]
        at com.dsh105.echopet.api.SqlPetManager.createPetFromDatabase(SqlPetManager.java:140) ~[?:?]
        at com.dsh105.echopet.api.SqlPetManager.createPetFromDatabase(SqlPetManager.java:103) ~[?:?]
        at com.dsh105.echopet.api.PetManager.loadPets(PetManager.java:167) ~[?:?]
        at com.dsh105.echopet.listeners.PetOwnerListener$1.run(PetOwnerListener.java:183) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.jar:git-Paper-1168]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1168]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

**Comment by Techcable** [comment]
The database code is due for a significant rewrite, I'm surprised it's even usable in production.
For now I think I'm going to focus my effort on other areas :cry:
