### ISSUE TITLE
server crash, horse null hook

### ISSUE THREAD

**Issue by PhanaticD** [TechzoneMC/SonarPet#115]
https://pastebin.com/raw/WH57UrDs

**Comment by PhanaticD** [comment]
also got a wolf one:

```
[04:51:36] [Server thread/WARN]: java.lang.NullPointerException: GeneratedEntityWolfPet['Wolf Pet'/253032, l='plot_large', x=1323.51, y=66.00, z=-2969.87] has null hook!
[04:51:36] [Server thread/WARN]:    at net.techcable.sonarpet.nms.entities.type.GeneratedEntityWolfPet.checkSanity(Unknown Source)
[04:51:36] [Server thread/WARN]:    at net.techcable.sonarpet.nms.entities.type.GeneratedEntityWolfPet.B_(Unknown Source)
[04:51:36] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1750)
[04:51:36] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.World.h(World.java:1720)
[04:51:36] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1537)
[04:51:36] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675)
[04:51:36] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:910)
[04:51:36] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[04:51:36] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
[04:51:36] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
[04:51:36] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[04:51:36] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception ticking world entities
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1168]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException: GeneratedEntityWolfPet['Wolf Pet'/253033, l='plot_large', x=1323.51, y=66.78, z=-2969.87] has null hook!
    at net.techcable.sonarpet.nms.entities.type.GeneratedEntityWolfPet.checkSanity(Unknown Source) ~[?:?]
    at net.techcable.sonarpet.nms.entities.type.GeneratedEntityWolfPet.stopRiding(Unknown Source) ~[?:?]
    at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1530) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:910) ~[patched_1.12.jar:git-Paper-1168]
    ... 4 more
[04:51:36] [Server thread/ERROR]:   Cause of unexpected exception was
java.lang.NullPointerException: GeneratedEntityWolfPet['Wolf Pet'/253033, l='plot_large', x=1323.51, y=66.78, z=-2969.87] has null hook!
    at net.techcable.sonarpet.nms.entities.type.GeneratedEntityWolfPet.checkSanity(Unknown Source) ~[?:?]
    at net.techcable.sonarpet.nms.entities.type.GeneratedEntityWolfPet.stopRiding(Unknown Source) ~[?:?]
    at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1530) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:910) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) ~[patched_1.12.jar:git-Paper-1168]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1168]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

**Comment by Techcable** [comment]
Do you think you could find a way to reproduce this? So far I've been unable to do it while messing with mounting/dismounting.

**Comment by PhanaticD** [comment]
idk havent used the plugin in over a year
