### ISSUE TITLE
SonarPet broken in PaperSpigot 1.7.10

### ISSUE THREAD

**Issue by MrPowerGamerBR** [TechzoneMC/SonarPet#48]
```
[18:01:56] [Server thread/ERROR]: Error occurred while enabling SonarPet v1.1.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: ENDERMITE
	at com.dsh105.echopet.compat.api.config.PetItem.<clinit>(PetItem.java:43) ~[?:?]
	at com.dsh105.echopet.compat.api.util.menu.SelectorLayout.getDefaultLayout(SelectorLayout.java:129) ~[?:?]
	at com.dsh105.echopet.compat.api.config.ConfigOptions.setDefaults(ConfigOptions.java:155) ~[?:?]
	at com.dsh105.echopet.libs.com.dsh105.commodus.config.Options.<init>(Options.java:34) ~[?:?]
	at com.dsh105.echopet.compat.api.config.ConfigOptions.<init>(ConfigOptions.java:39) ~[?:?]
	at com.dsh105.echopet.EchoPetPlugin.loadConfiguration(EchoPetPlugin.java:188) ~[?:?]
	at com.dsh105.echopet.EchoPetPlugin.onEnable(EchoPetPlugin.java:118) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:477) [dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:395) [dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:359) [dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:333) [dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:289) [dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:240) [dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:504) [dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [dreamspigot-1.7.10-R0.1-SNAPSHOT.jar:git-DreamSpigot-a648f3d]
```

**Comment by Techcable** [comment]
Since 1.7.10 is such an old version, I don't provide any support for free.
You may choose to either buy the plugin, or submit a pull request to get this issue fixed :)

**Comment by MrPowerGamerBR** [comment]
@Techcable I was going to buy it after testing the plugin.

Welp, time to get my hands dirty then.

**Comment by MrPowerGamerBR** [comment]
...or maybe not, I will try to get a bit of money to buy SonarPet, but, after taking a quick look, the issue is on the PetConfig, because there isn't a separate config for every version.

**Comment by TechDragon294** [comment]
He knows the issue (its pretty obvious).....
He just doesn't want to waste time on it until you pay him.
