### ISSUE TITLE
errror when spawning mushroomcow

### ISSUE THREAD

**Issue by PhanaticD** [TechzoneMC/SonarPet#72]
```
[18:13:17] [Server thread/INFO]: PhanaticD issued server command: /pet mushroomcow
[18:13:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet mushroomcow' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[patched_1.9.4.jar:git-Paper-772]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.9.4.jar:git-Paper-772]
    at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-772]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-772]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-772]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-772]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-772]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-772]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-772]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-772]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-772]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-772]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: com.dsh105.echopet.compat.api.registration.PetRegistrationException: java.lang.IllegalStateException: Failed to create pet object for PhanaticD
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:121) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-772]
    ... 14 more
Caused by: java.lang.IllegalStateException: Failed to create pet object for PhanaticD
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:85) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-772]
    ... 14 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-772]
    ... 14 more
Caused by: java.lang.IllegalStateException: Failed to create EntityPet object for PhanaticD
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:99) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:142) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_9_R2.NMSImpl.spawn(NMSImpl.java:104) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_9_R2.NMSImpl.spawn(NMSImpl.java:49) ~[?:?]
    at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:73) ~[?:?]
    at com.dsh105.echopet.api.pet.type.MushroomCowPet.<init>(MushroomCowPet.java:33) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-772]
    ... 14 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:91) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:142) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_9_R2.NMSImpl.spawn(NMSImpl.java:104) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_9_R2.NMSImpl.spawn(NMSImpl.java:49) ~[?:?]
    at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:73) ~[?:?]
    at com.dsh105.echopet.api.pet.type.MushroomCowPet.<init>(MushroomCowPet.java:33) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-772]
    ... 14 more
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R2.entity.CraftMushroomCow cannot be cast to org.bukkit.craftbukkit.v1_9_R2.entity.CraftChicken
    at com.dsh105.echopet.compat.nms.v1_9_R2.entity.type.EntityMushroomCowPet.getBukkitEntity(EntityMushroomCowPet.java:96) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_9_R2.entity.type.EntityMushroomCowPet.getBukkitEntity(EntityMushroomCowPet.java:46) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_9_R2.entity.EntityInsentientPet.initiateEntityPet(EntityInsentientPet.java:99) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_9_R2.entity.EntityAgeablePet.initiateEntityPet(EntityAgeablePet.java:78) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_9_R2.entity.type.EntityMushroomCowPet.<init>(EntityMushroomCowPet.java:91) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:91) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:142) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_9_R2.NMSImpl.spawn(NMSImpl.java:104) ~[?:?]
    at com.dsh105.echopet.compat.nms.v1_9_R2.NMSImpl.spawn(NMSImpl.java:49) ~[?:?]
    at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:73) ~[?:?]
    at com.dsh105.echopet.api.pet.type.MushroomCowPet.<init>(MushroomCowPet.java:33) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
    at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?]
    at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?]
    at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?]
    at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?]
    at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?]
    at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-772]
    ... 14 more
```

**Comment by Techcable** [comment]
Should be fixed as of build 45
