### ISSUE TITLE
v1_8_R3 broken

### ISSUE THREAD

**Issue by coelho** [TechzoneMC/SonarPet#73]
The new templating for NMS versions seems to have broken v1_8_R3.

```
[17:05:15] [Server thread/INFO]: [SonarPet] Enabling SonarPet v1.1.0-SNAPSHOT
[17:05:15] [Server thread/ERROR]: Error occurred while enabling SonarPet v1.1.0-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_91]
        at com.dsh105.echopet.compat.api.entity.PetType.<init>(PetType.java:96) ~[?:?]
        at com.dsh105.echopet.compat.api.entity.PetType.<clinit>(PetType.java:32) ~[?:?]
        at com.dsh105.echopet.compat.api.registration.PetRegistry.<init>(PetRegistry.java:67) ~[?:?]
        at com.dsh105.echopet.EchoPetPlugin.onEnable(EchoPetPlugin.java:124) ~[?:?]
        at net.techcable.sonarpet.Bootstrap.onEnable(Bootstrap.java:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-a861cc6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-PaperSpigot-a861cc6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-PaperSpigot-a861cc6]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:285) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [spigot.jar:git-PaperSpigot-a861cc6]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:142) [spigot.jar:git-PaperSpigot-a861cc6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:665) [spigot.jar:git-PaperSpigot-a861cc6]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1188) [spigot.jar:git-PaperSpigot-a861cc6]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000) [spigot.jar:git-PaperSpigot-a861cc6]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-PaperSpigot-a861cc6]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-PaperSpigot-a861cc6]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-a861cc6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-a861cc6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772) [spigot.jar:git-PaperSpigot-a861cc6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-a861cc6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot.jar:git-PaperSpigot-a861cc6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot.jar:git-PaperSpigot-a861cc6]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: Expected type boolean isn't assignable from double
        at net.techcable.sonarpet.utils.reflection.SonarField.getField(SonarField.java:127) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_8_R3.entity.EntityInsentientPet.<clinit>(EntityInsentientPet.java:50) ~[?:?]
        ... 29 more
```

As well, in Versioning.java, v1_8_R3 isn't in the enumeration, so it doesn't even recognize it as a version unless you manually patch it. 

https://github.com/TechzoneMC/SonarPet/blob/master/api/src/main/java/net/techcable/sonarpet/utils/Versioning.java#L49

**Comment by Techcable** [comment]
Looks like I messed obfuscation up for 1.8.8 in the transition to templates -_-
Also it looks like removing `v1_8_R3` was caused by [f32fd7b4d148e26aaafa216f5da625647feeb353](https://github.com/TechzoneMC/SonarPet/commit/f32fd7b4d148e26aaafa216f5da625647feeb353#diff-32f84d1495a61a08e413f03297342c8fL49), so at least I didn't do that one!

**Comment by coelho** [comment]
I reverted to commit ff46eae37770d02c4794d5738918c982a27853ee (right before the templating) and patched Versioning.java and then v1_8_R3 worked fine, so this'll probably be a semi-easy fix.
