### ISSUE TITLE
.NoSuchMethodError: org.bukkit.inventory.EntityEquipment.setItemInMainHand(Lorg/bukkit/inventory/ItemStack;)V

### ISSUE THREAD

**Issue by L4BORG** [TechzoneMC/SonarPet#89]
```
[20:20:13 WARN]: [SonarPet] Task #78 for SonarPet v1.1.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.EntityEquipment.setItemInMainHand(Lorg/bukkit/inventory/ItemStack;)V
        at net.techcable.sonarpet.nms.entity.AbstractEntityZombiePet$1.run(AbstractEntityZombiePet.java:28) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

**Comment by L4BORG** [comment]
I guess using deprecated setItemInHand() will fix this.
