### ISSUE TITLE
Incompatible with latest Citizens

### ISSUE THREAD

**Issue by VoidAngel** [TechzoneMC/SonarPet#95]
I'm not sure if this is a paper spigot thing or not, but when trying to load the newest release (1.1.0-alpha1) I get this error. Is it only 1.11 (strictly) that is currently supported?

````18.05 05:08:31 [Server] INFO [SonarPet] Enabling SonarPet v1.1.0-alpha1-release
18.05 05:08:31 [Server] WARN Enabled plugin with unregistered PluginClassLoader SonarPet v1.1.0-alpha1-release
18.05 05:08:31 [Server] ERROR Error occurred while enabling SonarPet v1.1.0-alpha1-release (Is it up to date?)
18.05 05:08:31 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: -1
18.05 05:08:31 [Server] INFO at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_131]
18.05 05:08:31 [Server] INFO at java.util.ArrayList.set(ArrayList.java:446) ~[?:1.8.0_131]
18.05 05:08:31 [Server] INFO at net.minecraft.server.v1_11_R1.EntityTypes.a(SourceFile:359) ~[paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at net.techcable.sonarpet.nms.versions.v1_11_R1.NMSEntityRegistry.registerEntityClass(NMSEntityRegistry.java:31) ~[?:?]
18.05 05:08:31 [Server] INFO at net.techcable.sonarpet.HookRegistryImpl.registerHookClass(HookRegistryImpl.kt:34) ~[?:?]
18.05 05:08:31 [Server] INFO at com.dsh105.echopet.EchoPetPlugin.onEnable(EchoPetPlugin.java:195) ~[?:?]
18.05 05:08:31 [Server] INFO at net.techcable.sonarpet.Bootstrap.onEnable(Bootstrap.java:57) ~[?:?]
18.05 05:08:31 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at com.massivecraft.massivelag.inject.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:215) [MassiveLag.jar:?]
18.05 05:08:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [paperclip.jar:git-Paper-1082]
18.05 05:08:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
18.05 05:08:31 [Server] INFO [SonarPet] Disabling SonarPet v1.1.0-alpha1-release````

**Comment by Techcable** [comment]
Seems to be fixed as of [build 9](https://ci.techcable.net/job/SonarPet/9/) for me. Just reopen if it still doesn't work.

**Comment by Techcable** [comment]
Upon further inspection, this appears to be an incompatibility with Citizens.
